### ISSUE TITLE
[pvr] NextPVR dialog causes crash, works with other skins

### ISSUE THREAD

**Issue by vonH** [vonH/skin.xperience1080#23]
"When I try to record a show, this dialogue comes up. I can record shows by switching to other skins so I don't think it is a Kodi issue. Hitting anything other than close crashes Kodi."

"I haven't seen anyone else have this issue so I would say it's only me, but I cannot figure out what could be the problem."

Source: http://forum.kodi.tv/showthread.php?tid=219589&pid=2083474#pid2083474

**Comment by vonH** [comment]
@xhaggi Have you had a chance to look at this?

**Comment by vonH** [comment]
@xhaggi

**Comment by JonathanHolvey** [comment]
For what it's worth, I can tell you that I use NPVR with Xperience1080 and I don't have the problem described. Nothing happens when clicking OK or Close, but with a custom RecordPrefs.xml file the recordings are set correctly.

However, I believe that the recording function will be included natively in Kodi 16, so RecordPrefs.xml won't be required.
